site_name: MoBrix-ui documentation
repo_url: https://github.com/CianciarusoCataldo/mobrix-ui
site_author: Cataldo Cianciaruso
copyright: 2024 Cataldo Cianciaruso
theme:
  logo: "assets/mobtix-ui_icon.svg" 
  favicon: "assets/mobtix-ui_icon.svg" 
  name: material
  features:
   - navigation.instant
  custom_dir: docs-gen/templates/published
  palette: 
    - scheme: default
      toggle:
        icon: material/weather-night 
        name: Switch to dark mode
    - scheme: slate
      primary: blue grey
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode